CREATE DATABASE ONG_PET;
USE ONG_PET;

CREATE TABLE ASSOCIADO
	(
	 ID	      		INT NOT NULL,
	 NOME     		VARCHAR(70) NOT NULL,
	 SEXO			CHAR(1) NOT NULL,
	 DT_NASC	    DATETIME NOT NULL,
	 CPF	      	VARCHAR(11) NOT NULL,
	 EMAIL	      	VARCHAR(50) NOT NULL,
	 ESTADO_CIVIL	CHAR(1) NOT NULL,
	 LOGRADOURO	    VARCHAR(30) NOT NULL,
	 NUMERO	      	INT NOT NULL,
	 BAIRRO	      	VARCHAR(20) NOT NULL,
	 CIDADE	      	VARCHAR(30) NOT NULL,
	 ESTADO	      	CHAR(2) NOT NULL,
	 CONSTRAINT PK_ASSOCIADO PRIMARY KEY (ID)
	)
GO

CREATE TABLE AREANEGOCIO
	(
	 ID	      		INT NOT NULL,
	 CODIGO		    INT NOT NULL,
	 DESCRICAO		VARCHAR(20) NOT NULL,
	 ID_AREANEGOCIO	INT NOT NULL,
	 CONSTRAINT PK_AREANEGOCIO PRIMARY KEY (ID)
	)
GO

CREATE TABLE SETOR
	(
	 ID	      		INT NOT NULL,
	 CODIGO    		INT NOT NULL,
	 DESCRICAO		VARCHAR(100) NOT NULL,
	 CONSTRAINT PK_SETOR PRIMARY KEY (ID)
	)
GO

CREATE TABLE ANIMAL
	(
	 ID	      		INT NOT NULL,
	 ESPECIE     	VARCHAR(70) NOT NULL,
	 NOME 			VARCHAR(30) NULL,
	 RACA			VARCHAR(30) NOT NULL,
	 DT_ADOCAO	    DATETIME NOT NULL,
	 DESCRICAO     	VARCHAR(150) NOT NULL,
	 DISP_ADOCAO   	CHAR(1) NOT NULL,
	 MORTO			CHAR(1) NOT NULL,
	 DT_MORTE	    DATETIME NOT NULL,
	 ID_ASSOCIADO	INT NULL,
	 CONSTRAINT PK_ANIMAL PRIMARY KEY (ID),
	 CONSTRAINT FK_ANIMAL_ASSOCIADO FOREIGN KEY (ID_ASSOCIADO)
        REFERENCES ASSOCIADO (ID)
	)
GO

CREATE TABLE FUNCIONARIO
	(
	 ID	      		INT NOT NULL,
	 NOME     		VARCHAR(70) NOT NULL,
	 SEXO			CHAR(1) NOT NULL,
	 DT_NASC	    DATETIME NOT NULL,
	 CPF	      	VARCHAR(11) NOT NULL,
	 EMAIL	      	VARCHAR(50) NOT NULL,
	 SALARIO		DOUBLE NOT NULL,
	 NIVEL_ADM		CHAR(1) NOT NULL, --SE É ADM OU NÃO (S,N)
	 ESTADO_CIVIL	CHAR(1) NOT NULL,
	 LOGRADOURO	    VARCHAR(30) NOT NULL,
	 NUMERO	      	INT NOT NULL,
	 BAIRRO	      	VARCHAR(20) NOT NULL,
	 CIDADE	      	VARCHAR(30) NOT NULL,
	 ESTADO	      	CHAR(2) NOT NULL,
	 ID_SETOR		INT NOT NULL,
	 CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (ID),
	 CONSTRAINT FK_FUNCIONARIO_SETOR FOREIGN KEY (ID_SETOR)
        REFERENCES SETOR (ID)
	)
GO

CREATE TABLE USUARIO
	(
	 ID	      		INT NOT NULL,
	 NOME     		VARCHAR(70) NOT NULL,
	 SEXO			CHAR(1) NOT NULL,
	 DT_NASC	    DATETIME NOT NULL,
	 CPF	      	VARCHAR(11) NOT NULL,
	 EMAIL	      	VARCHAR(50) NOT NULL,
	 ID_FUNCIONARIO INT NULL,
	 ID_ASSOCIADO	INT NULL,
	 CONSTRAINT PK_USUARIO PRIMARY KEY (ID),
	 CONSTRAINT FK_USUARIO_FUNCIONARIO FOREIGN KEY (ID_FUNCIONARIO)
        REFERENCES FUNCIONARIO (ID),
     CONSTRAINT FK_USUARIO_ASSOCIADO FOREIGN KEY (ID_ASSOCIADO)
        REFERENCES ASSOCIADO (ID)
	)
GO

--Pra que serve a medição? é preciso separar em uma tabela e vincular ao animal?

CREATE TABLE TIPOMEDICAO
	(
	 ID	      		INT NOT NULL,
	 MES     		INT NOT NULL,
	 ANO 			INT NOT NULL,
	 ID_ANIMAL		INT NULL,
	 CONSTRAINT PK_TIPOMEDICAO PRIMARY KEY (ID),
	 CONSTRAINT FK_TIPOMEDICAO_ANIMAL FOREIGN KEY (ID_ANIMAL)
        REFERENCES ANIMAL (ID)
	)
GO

CREATE TABLE DOACAO
	(
	 ID	      		INT NOT NULL,
	 VALOR     		DOUBLE NOT NULL,
	 ID_ASSOCIADO	INT NOT NULL,
	 CONSTRAINT PK_DOACAO PRIMARY KEY (ID),
	 CONSTRAINT FK_DOACAO_ASSOCIADO FOREIGN KEY (ID_ASSOCIADO)
        REFERENCES ASSOCIADO (ID)
	)
GO

CREATE TABLE ADOCAO
	(
	 ID	      		INT NOT NULL,
	 DT_ADOCAO	    DATETIME NOT NULL,
	 ID_ANIMAL	    INT NOT NULL,
	 ID_ASSOCIADO	INT NOT NULL,
	 CONSTRAINT PK_ADOCAO PRIMARY KEY (ID),
	 CONSTRAINT FK_ADOCAO_ANIMAL FOREIGN KEY (ID_ANIMAL)
        REFERENCES ANIMAL (ID),
     CONSTRAINT FK_ADOCAO_ASSOCIADO FOREIGN KEY (ID_ASSOCIADO)
        REFERENCES ASSOCIADO (ID)
	)
GO

CREATE TABLE PARCEIRO
	(
	 ID	      		INT NOT NULL,
	 NOME		    VARCHAR(70) NOT NULL,
	 CNPJ		    VARCHAR(14) NOT NULL,
	 ID_AREANEGOCIO	INT NOT NULL,
	 CONSTRAINT PK_PARCEIRO PRIMARY KEY (ID),
	 CONSTRAINT FK_PARCEIRO_AREANEGOCIO FOREIGN KEY (ID_AREANEGOCIO)
        REFERENCES AREANEGOCIO (ID),
	)
GO

CREATE TABLE ATENDIMENTO
	(
	 ID	      		INT NOT NULL,
	 DT_ATENDIMENTO DATETIME NOT NULL,
	 RACA	      	VARCHAR(30) NOT NULL,
	 TIPO	      	VARCHAR(20) NOT NULL,
	 DESCRICAO		VARCHAR(200) NOT NULL,
	 ID_FUNCIONARIO	INT NOT NULL,
	 CONSTRAINT PK_ATENDIMENTO PRIMARY KEY (ID),
	 CONSTRAINT FK_ATENDIMENTO_FUNCIONARIO FOREIGN KEY (ID_FUNCIONARIO)
        REFERENCES FUNCIONARIO (ID)
	)
GO

*/
/*
TABELAS NECESSÁRIAS

OK USUARIO
OK FUNCIONARIO
OK SETOR
OK DOACAO
OK ADOCAO
OK ANIMAL
OK ASSOCIADO
OK TIPOMEDICAO
OK ATENDIMENTO
OK AREA_NEGOCIO -- RAMO
OK PARCEIRO
*/