CREATE DATABASE ONG_PET;
USE ONG_PET;

DROP TABLE dbo.ASSOCIADO;
DROP TABLE dbo.AREANEGOCIO;
DROP TABLE dbo.SETOR;
DROP TABLE dbo.ANIMAL;
DROP TABLE dbo.FUNCIONARIO;
DROP TABLE dbo.DOACAO;
DROP TABLE dbo.ADOCAO;
DROP TABLE dbo.PARCEIRO; 
DROP TABLE dbo.TIPOMEDICAO;
DROP TABLE dbo.ATENDIMENTO;

CREATE TABLE ASSOCIADO
	(
	 ID	      		BIGINT IDENTITY(1,1) NOT NULL,
	 NOME     		VARCHAR(70) NOT NULL,
	 DATANASCIMENTO	    DATE NOT NULL,
	 CPF	      	VARCHAR(11) NOT NULL,
	 EMAIL	      	VARCHAR(50) NOT NULL,
	 SENHA	      	VARCHAR(50) NOT NULL,
	 CONSTRAINT PK_ASSOCIADO PRIMARY KEY (ID)
	)
GO

CREATE TABLE AREANEGOCIO
	(
	 ID	      		INT NOT NULL,
	 CODIGO		    INT NOT NULL,
	 DESCRICAO		VARCHAR(20) NOT NULL,
	 ID_AREANEGOCIO	INT NOT NULL,
	 CONSTRAINT PK_AREANEGOCIO PRIMARY KEY (ID)
	)
GO

CREATE TABLE ANIMAL
	(
	 ID	      		BIGINT NOT NULL,
	 ESPECIE     	VARCHAR(70) NOT NULL,
	 NOME 			VARCHAR(30) NULL,
	 RACA			VARCHAR(30) NOT NULL,
	 IDADE			INTEGER NOT NULL,
	 MEDICAO_IDADE	BIT NOT NULL,
	 DT_ADOCAO	    DATETIME NOT NULL,
	 DESCRICAO     	VARCHAR(150) NOT NULL,
	 DISP_ADOCAO   	BIT NOT NULL,
	 MORTO			BIT NOT NULL,
	 ID_ASSOCIADO	INT NULL,
	 CONSTRAINT PK_ANIMAL PRIMARY KEY (ID),
	 CONSTRAINT FK_ANIMAL_ASSOCIADO FOREIGN KEY (ID_ASSOCIADO)
        REFERENCES ASSOCIADO (ID)
	)
GO

CREATE TABLE FUNCIONARIO
	(
	 ID	      			BIGINT IDENTITY(1,1) NOT NULL,
	 NOME     			VARCHAR(70) NOT NULL,
	 DATANASCIMENTO	    DATE NOT NULL,
	 CPF	      		VARCHAR(11) NOT NULL,
	 EMAIL	      		VARCHAR(50) NOT NULL,
	 SENHA				VARCHAR(50) NOT NULL,
	 SALARIO			FLOAT NOT NULL,
	 ISADMINISTRADOR	BIT NOT NULL,
	 SETOR				INT NOT NULL,
	 CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (ID)
	)
GO

CREATE TABLE DOACAO
	(
	 ID	      		INT NOT NULL,
	 VALOR     		DECIMAL NOT NULL,
	 ID_ASSOCIADO	INT NOT NULL,
	 CONSTRAINT PK_DOACAO PRIMARY KEY (ID),
	 CONSTRAINT FK_DOACAO_ASSOCIADO FOREIGN KEY (ID_ASSOCIADO)
        REFERENCES ASSOCIADO (ID)
	)
GO

CREATE TABLE ADOCAO
	(
	 ID	      		BIGINT NOT NULL,
	 DT_ADOCAO	    DATETIME NOT NULL,
	 ID_ANIMAL	    INT NOT NULL,
	 ID_ASSOCIADO	INT NOT NULL,
	 CONSTRAINT PK_ADOCAO PRIMARY KEY (ID),
	 CONSTRAINT FK_ADOCAO_ANIMAL FOREIGN KEY (ID_ANIMAL)
        REFERENCES ANIMAL (ID),
     CONSTRAINT FK_ADOCAO_ASSOCIADO FOREIGN KEY (ID_ASSOCIADO)
        REFERENCES ASSOCIADO (ID)
	)
GO

CREATE TABLE PARCEIRO
	(
	 ID	      		BIGINT IDENTITY(1,1) NOT NULL,
	 NOME		    VARCHAR(70) NOT NULL,
	 CNPJ		    VARCHAR(14) NOT NULL,
	 RAMO		    VARCHAR(14) NOT NULL,
	 CONSTRAINT PK_PARCEIRO PRIMARY KEY (ID),
	)
GO

CREATE TABLE ATENDIMENTO
	(
	 ID	      			BIGINT IDENTITY(1,1) NOT NULL,
	 DATAATENDIMENTO	DATETIME NOT NULL,
	 RACA	      		VARCHAR(30) NOT NULL,
	 TIPOATENDIMENTO	      		VARCHAR(20) NOT NULL,
	 DESCRICAO			VARCHAR(200) NOT NULL,
	 FUNCIONARIOID		BIGINT NOT NULL,
	 CONSTRAINT PK_ATENDIMENTO PRIMARY KEY (ID),
	 CONSTRAINT FK_ATENDIMENTO_FUNCIONARIO FOREIGN KEY (FUNCIONARIOID)
        REFERENCES FUNCIONARIO (ID)
	)
GO

/*
TABELAS NECESSÁRIAS

OK USUARIO
OK FUNCIONARIO
OK SETOR
OK DOACAO
OK ADOCAO
OK ANIMAL
OK ASSOCIADO
OK TIPOMEDICAO
OK ATENDIMENTO
OK AREA_NEGOCIO -- RAMO
OK PARCEIRO
*/
