--DROP TABLE dbo.ASSOCIADO;
--DROP TABLE dbo.AREANEGOCIO;
--DROP TABLE dbo.SETOR;
--DROP TABLE dbo.ANIMAL;
--DROP TABLE dbo.FUNCIONARIO;
--DROP TABLE dbo.DOACAO;
--DROP TABLE dbo.ADOCAO;
--DROP TABLE dbo.PARCEIRO; 
--DROP TABLE dbo.TIPOMEDICAO;
--DROP TABLE dbo.ATENDIMENTO;

CREATE TABLE ASSOCIADO
	(
	 ID	      		BIGINT IDENTITY(1,1) NOT NULL,
	 NOME     		VARCHAR(70) NOT NULL,
	 DATANASCIMENTO	    DATE NOT NULL,
	 CPF	      	VARCHAR(11) NOT NULL,
	 EMAIL	      	VARCHAR(50) NOT NULL,
	 SENHA	      	VARCHAR(50) NOT NULL,
	 CONSTRAINT PK_ASSOCIADO PRIMARY KEY (ID)
	)
GO

CREATE TABLE ANIMAL
	(
	 ID	      				BIGINT IDENTITY(1,1) NOT NULL,
	 ESPECIE     			VARCHAR(70) NOT NULL,
	 NOME 					VARCHAR(30) NULL,
	 RACA					VARCHAR(30) NOT NULL,
	 IDADE					INTEGER NOT NULL,
	 MEDICAOIDADE			INTEGER NOT NULL,
	 DESCRICAO     			VARCHAR(150) NOT NULL,
	 ISDISPONIVELPARAADOCAO BIT NOT NULL,
	 ISMORTO				BIT NOT NULL,
	 ADOTANTEID				BIGINT NULL,
	 CONSTRAINT PK_ANIMAL PRIMARY KEY (ID),
	 CONSTRAINT FK_ANIMAL_ASSOCIADO FOREIGN KEY (ADOTANTEID)
        REFERENCES ASSOCIADO (ID)
	)
GO

CREATE TABLE FUNCIONARIO
	(
	 ID	      			BIGINT IDENTITY(1,1) NOT NULL,
	 NOME     			VARCHAR(70) NOT NULL,
	 DATANASCIMENTO	    DATE NOT NULL,
	 CPF	      		VARCHAR(11) NOT NULL,
	 EMAIL	      		VARCHAR(50) NOT NULL,
	 SENHA				VARCHAR(50) NOT NULL,
	 SALARIO			FLOAT NOT NULL,
	 ISADMINISTRADOR	BIT NOT NULL,
	 SETOR				INT NOT NULL,
	 CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (ID)
	)
GO

CREATE TABLE DOACAO
	(
	 ID	      		BIGINT IDENTITY(1,1) NOT NULL,
	 VALOR     		FLOAT NOT NULL,
	 ASSOCIADOID	BIGINT NOT NULL,
	 CONSTRAINT PK_DOACAO PRIMARY KEY (ID),
	 CONSTRAINT FK_DOACAO_ASSOCIADO FOREIGN KEY (ASSOCIADOID)
        REFERENCES ASSOCIADO (ID)
	)
GO

CREATE TABLE PARCEIRO
	(
	 ID	      		BIGINT IDENTITY(1,1) NOT NULL,
	 NOME		    VARCHAR(70) NOT NULL,
	 CNPJ		    VARCHAR(14) NOT NULL,
	 RAMO		    VARCHAR(14) NOT NULL,
	 CONSTRAINT PK_PARCEIRO PRIMARY KEY (ID),
	)
GO

CREATE TABLE ATENDIMENTO
	(
	 ID	      			BIGINT IDENTITY(1,1) NOT NULL,
	 DATAATENDIMENTO	DATETIME NOT NULL,
	 RACA	      		VARCHAR(30) NOT NULL,
	 TIPOATENDIMENTO	      		VARCHAR(20) NOT NULL,
	 DESCRICAO			VARCHAR(200) NOT NULL,
	 FUNCIONARIOID		BIGINT NOT NULL,
	 CONSTRAINT PK_ATENDIMENTO PRIMARY KEY (ID),
	 CONSTRAINT FK_ATENDIMENTO_FUNCIONARIO FOREIGN KEY (FUNCIONARIOID)
        REFERENCES FUNCIONARIO (ID)
	)
GO

/*
TABELAS NECESSÁRIAS

OK USUARIO
OK FUNCIONARIO
OK SETOR
OK DOACAO
OK ADOCAO
OK ANIMAL
OK ASSOCIADO
OK TIPOMEDICAO
OK ATENDIMENTO
OK AREA_NEGOCIO -- RAMO
OK PARCEIRO
*/
